//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FancyError {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FancyError.ErrorTemplate", typeof(ErrorTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;title&gt;Sorry, we&apos;ve run into an error | {APP_TITLE}&lt;/title&gt;
        ///
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        {STYLESHEET}
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;fancyerror-header&quot;&gt;
        ///        &lt;h1&gt;
        ///            Sorry, it seems we&apos;ve run into a problem.
        ///        &lt;/h1&gt;
        ///    &lt;/div&gt;
        ///    &lt;div id=&quot;fancyerror-body&quot;&gt;
        ///        &lt;div id=&quot;fancyerror-sidebar&quot;&gt;
        ///            &lt;div class=&quot;outage-data potential-outage {OUTAGE}&quot;&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasePage {
            get {
                return ResourceManager.GetString("BasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this time we would suggest visiting our &lt;a class=&quot;status-link&quot; href=&quot;{STATUS_URL}&quot;&gt;application status page&lt;/a&gt; to view information about current known issues..
        /// </summary>
        internal static string StatusPageText {
            get {
                return ResourceManager.GetString("StatusPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    font-family:&apos;Segoe UI&apos;, Tahoma, Geneva, Verdana, sans-serif;
        ///    background-color:#860000
        ///}
        ///
        ///#fancyerror-header {
        ///    font-weight: bold;
        ///    text-align: center;
        ///
        ///
        ///    background-color: #aa0000;
        ///    color: #ffffff;
        ///    text-shadow: 2px 2px #000000;
        ///
        ///    padding: 5px;
        ///    width: 50%;
        ///    margin: auto;
        ///
        ///    border-radius: 10px;
        ///    margin-top: 50px;
        ///}
        ///
        ///#fancyerror-header h1 {
        ///    font-size: 25pt;
        ///}
        ///
        ///#fancyerror-body {
        ///    width: 50%;
        ///    margin: auto;
        ///    margin-top: 20p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StyleSheet {
            get {
                return ResourceManager.GetString("StyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;If you believe this issue is something that needs to be investigated, then we&apos;d ask that you please submit a support ticket to our team, who will investigate the issue. Please ensure to provide the error information, listed on the left side of the page.&lt;/p&gt;
        ///
        ///&lt;p&gt;&lt;a class=&quot;support-link&quot; href=&quot;{SUPPORT_URL}&quot;&gt;Submit a Support Request&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        internal static string SupportPageText {
            get {
                return ResourceManager.GetString("SupportPageText", resourceCulture);
            }
        }
    }
}
